-- APPLIED as migration `listvault_us_seed_questions`.
-- 60 curated couple questions, 15 per mood.
insert into public.lv_questions (text, mood) values
-- fun
('If we opened a tiny café together, what would it be called and what would be on the menu?', 'fun'),
('What movie do you secretly want us to watch together even though you think I''d judge you?', 'fun'),
('If we could teleport anywhere in Mumbai right now for two hours, where are we going?', 'fun'),
('Which fictional couple are we most like — and which one should we aspire to be?', 'fun'),
('What would the title of a Bollywood film about us be?', 'fun'),
('If I had a superpower based on my habits, what would it be?', 'fun'),
('What''s the weirdest food combination you actually enjoy and want me to try?', 'fun'),
('If we swapped phones for a day, what would surprise me most?', 'fun'),
('What song do you play when you think of me?', 'fun'),
('If animals could talk, which one would be the rudest about our relationship?', 'fun'),
('What''s one thing I do that would make a hilarious viral reel?', 'fun'),
('If we got to design a public holiday together, what would it celebrate?', 'fun'),
('Which emoji do you think describes me best, and why?', 'fun'),
('What would you do with one day of total invisibility — and would you include me?', 'fun'),
('If our chats were published as a book, what would the reviews say?', 'fun'),
-- memories
('What was the exact moment you knew you liked me?', 'memories'),
('Which small, ordinary day with me do you think about more than any big occasion?', 'memories'),
('What''s the funniest thing that happened to us that we never talk about?', 'memories'),
('What food will forever remind you of us?', 'memories'),
('What''s a place we''ve been together that you want to go back to, exactly as it was?', 'memories'),
('What did you think about me the very first time we met — honestly?', 'memories'),
('Which photo of us is your favourite, and what was happening just outside the frame?', 'memories'),
('What''s something I said once that you never forgot?', 'memories'),
('When did I make you laugh the hardest?', 'memories'),
('What was the hardest week we''ve had, and what got us through it?', 'memories'),
('Which of our firsts do you remember most clearly — first call, first trip, first fight?', 'memories'),
('What''s a tiny detail about me you noticed early on and never mentioned?', 'memories'),
('If you could relive one hour we spent together, which one?', 'memories'),
('What tradition have we accidentally created that you hope we never lose?', 'memories'),
('What''s the best gift I''ve given you — not by price, but by feeling?', 'memories'),
-- preferences
('What''s your ideal Saturday with me — hour by hour?', 'preferences'),
('Big crowded festival or tiny quiet plan: which is your real preference and why?', 'preferences'),
('What kind of surprise do you actually enjoy — and what kind do you only pretend to?', 'preferences'),
('When you''ve had a terrible day, what do you want from me: solutions, silence, or snacks?', 'preferences'),
('What''s one thing you wish we did more often together?', 'preferences'),
('How do you actually like to be comforted when you''re sad?', 'preferences'),
('Street food adventure or fancy dinner — where am I taking you and why?', 'preferences'),
('What time of day do you feel most yourself?', 'preferences'),
('What''s a hobby you''d love us to try together, even badly?', 'preferences'),
('How much alone time do you need in a week to feel good?', 'preferences'),
('What''s your favourite way I show you I care — and one way I haven''t tried yet?', 'preferences'),
('Planned itinerary or zero plans: what''s the perfect trip style for you?', 'preferences'),
('Which chore or errand would you happily hand over to me forever?', 'preferences'),
('What''s something small I could do every week that would make you feel loved?', 'preferences'),
('Monsoon walk, winter morning, or summer night — pick our weather and the plan that goes with it.', 'preferences'),
-- deeper
('What''s something you''re proud of that you feel you never got enough credit for?', 'deeper'),
('What fear have you never said out loud to me?', 'deeper'),
('When do you feel closest to me — and when do you feel furthest?', 'deeper'),
('What''s one thing you need more of from me right now?', 'deeper'),
('What did your family teach you about love that you want to keep — and what do you want to unlearn?', 'deeper'),
('What does "home" mean to you, and when have you felt it most?', 'deeper'),
('What''s a dream you''ve quietly shelved that you might want to take down again?', 'deeper'),
('What are you most afraid of losing?', 'deeper'),
('In what ways have I changed you?', 'deeper'),
('What conversation have we been avoiding?', 'deeper'),
('What does being supported look like to you when you''re struggling?', 'deeper'),
('Where do you hope we are in five years — honestly, not the polished answer?', 'deeper'),
('What''s something about yourself you''re still learning to accept?', 'deeper'),
('When have you felt truly seen by me?', 'deeper'),
('What would you want me to know if you could plant one belief in my head forever?', 'deeper');
