#!/usr/bin/env python3
"""Regenerate db/fixture/schema.sql from a production pg_dump.

Usage: python3 scripts/extract-fixture-schema.py <path-to-dump.sql>

Keeps the fixture honest: table bodies are copied VERBATIM from the dump
(only the public. qualifier and `without time zone` noise stripped, FKs
omitted so the subset stands alone). If production changes shape, re-run
this against a fresh dump instead of editing the fixture by hand.
"""
import re, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else \
    '/root/.claude/uploads/9f0785d5-e6dc-5b79-93c2-71ac6d5ce42b/9590aa62-puchoschema.sql'
src = open(SRC).read()

TABLES = ['Language','ChannelPartner','Organization','User','OrganizationUser','Package',
          'OrganizationPackage','Payment','CreditWallets','CreditTransaction','FreeCreditUsage',
          'ChatHistory','ChatQuestion','LoginHistory','UsageTracking','Calls','WaitlistUser',
          'ContactSales','CampaignLead','CreditUsageError','SubscriptionUpgrade']

bodies = []
enum_refs = set()
for t in TABLES:
    m = re.search(r'(CREATE TABLE public\."%s" \(.*?\);)' % t, src, re.S)
    assert m, f'table {t} missing from dump'
    body = m.group(1)
    enum_refs.update(re.findall(r'\s(?:public\.)"([A-Z][A-Za-z]+)"(?:\s|,|\))', body))
    body = re.sub(r'public\."([A-Za-z]+)"', r'"\1"', body)
    body = body.replace(' without time zone', '')
    bodies.append(body)

# Every enum type actually referenced by the included tables, discovered from
# the dump itself rather than a hand-kept list.
all_enums = re.findall(r'CREATE TYPE public\."([A-Za-z]+)" AS ENUM', src)
enums = [e for e in all_enums if ('"%s"' % e) in '\n'.join(bodies)]

out = ['''-- ============================================================
-- FIXTURE SCHEMA — extracted VERBATIM from the production pg_dump
-- (PostgreSQL 17.4, dumped 17 Aug 2026).
--
-- GENERATED by scripts/extract-fixture-schema.py — do not hand-edit table
-- bodies; re-run the extractor against a fresh dump instead. Only the tables
-- and enums Pulse reads are included (DATA_MODEL.md §2); FK constraints are
-- stripped so the subset stands alone. Pulse's own tables come from
-- db/migrations/, exactly as they will in production.
-- ============================================================

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;
''']
for e in enums:
    m = re.search(r'(CREATE TYPE public\."%s" AS ENUM \(.*?\);)' % e, src, re.S)
    out.append(m.group(1).replace('public."%s"' % e, '"%s"' % e))
    out.append('')
out.extend(b + '\n' for b in bodies)
for t in TABLES:
    out.append('ALTER TABLE "%s" ADD PRIMARY KEY (id);' % t)

open('db/fixture/schema.sql', 'w').write('\n'.join(out) + '\n')
print(f'wrote db/fixture/schema.sql — {len(TABLES)} tables, {len(enums)} enums: {enums}')
