-- ============================================================
-- FIXTURE SCHEMA — extracted VERBATIM from the production pg_dump
-- (PostgreSQL 17.4, dumped 17 Aug 2026).
--
-- GENERATED by scripts/extract-fixture-schema.py — do not hand-edit table
-- bodies; re-run the extractor against a fresh dump instead. Only the tables
-- and enums Pulse reads are included (DATA_MODEL.md §2); FK constraints are
-- stripped so the subset stands alone. Pulse's own tables come from
-- db/migrations/, exactly as they will in production.
-- ============================================================

DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA public;

CREATE TYPE "CreditNoteStatus" AS ENUM (
    'open',
    'closed',
    'void'
);

CREATE TYPE "CreditType" AS ENUM (
    'PURCHASE',
    'BONUS',
    'REFERRAL',
    'TRANSFER',
    'ADJUSTMENT',
    'ROLLBACK',
    'MONTHLY_ALLOCATION',
    'RENEWAL'
);

CREATE TYPE "EntityType" AS ENUM (
    'USER',
    'ORGANIZATION',
    'CHANNEL_PARTNER'
);

CREATE TYPE "PayFrequency" AS ENUM (
    'DAILY',
    'WEEKLY',
    'MONTHLY',
    'QUARTERLY',
    'YEARLY',
    'ON_DEMAND'
);

CREATE TYPE "PaymentMethod" AS ENUM (
    'RAZORPAY',
    'UPI',
    'CHARGEBEE',
    'CARD'
);

CREATE TYPE "PaymentStatus" AS ENUM (
    'PENDING',
    'COMPLETED',
    'FAILED',
    'PAID',
    'CANCELED',
    'PROCESSING'
);

CREATE TYPE "SDRStatus" AS ENUM (
    'NEW',
    'RESEARCHING',
    'QUALIFIED',
    'DISQUALIFIED',
    'CONTACTED',
    'RESPONDED',
    'CONVERTED',
    'ARCHIVED',
    'MEETING_SCHEDULED',
    'MEETING_DONE',
    'INTERESTED',
    'NOT_INTERESTED'
);

CREATE TYPE "SocialLogin" AS ENUM (
    'Google'
);

CREATE TYPE "Status" AS ENUM (
    'Active',
    'Inactive',
    'Suspend',
    'Pending',
    'Deleted'
);

CREATE TYPE "TransactionType" AS ENUM (
    'ALLOCATION',
    'USAGE',
    'PURCHASE',
    'REFERRAL',
    'BONUS',
    'TRANSFER',
    'EXPIRE',
    'ADJUSTMENT',
    'RENEWAL',
    'CREDIT',
    'DEBIT',
    'REFUND'
);

CREATE TYPE "UserStatus" AS ENUM (
    'Active',
    'Inactive',
    'Suspend',
    'Pending',
    'Deleted'
);

CREATE TYPE "chatType" AS ENUM (
    'CHAT',
    'ORG_KNOWLEDGE',
    'NOTEBOOK',
    'PUCHO_PIECE',
    'WHATSAPP',
    'PUCHO_OFFICE_EXCEL_CHAT',
    'PUCHO_OFFICE_WORD_CHAT',
    'PUCHO_OFFICE_POWER_POINT_CHAT',
    'PUCHO_CODE_CHAT',
    'WHATSAPP_CHAT'
);

CREATE TABLE "Language" (
    id text NOT NULL,
    name text NOT NULL,
    code text,
    status "Status" NOT NULL,
    "order" text,
    "subName" text,
    "modelLangCode" text
);

CREATE TABLE "ChannelPartner" (
    id text NOT NULL,
    "userId" text NOT NULL,
    "companyName" text,
    "contactPerson" text,
    email text,
    "phoneNumber" text,
    address text,
    status "Status" DEFAULT 'Active'::"Status" NOT NULL,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    remarks text,
    "maxFreeOrgCredit" integer,
    "isCp2" boolean DEFAULT false NOT NULL,
    tier text
);

CREATE TABLE "Organization" (
    id text NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    "emailVerifiedAt" timestamp(3),
    "phoneNumber" text,
    "phoneNumberVerifiedAt" timestamp(3),
    status "Status" NOT NULL,
    remark text,
    "userId" text NOT NULL,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdBy" text,
    logo text,
    industry text,
    "showAgent" boolean DEFAULT true NOT NULL,
    "isAllowProviderSetting" boolean DEFAULT true NOT NULL,
    mcp_use boolean DEFAULT false NOT NULL,
    "multiModelUse" boolean DEFAULT false NOT NULL,
    "showVoiceAgent" boolean DEFAULT false NOT NULL,
    "channelPartnerId" text,
    "PayFrequency" "PayFrequency",
    "onboardingCharges" numeric(10,2) DEFAULT 0.00 NOT NULL,
    address text,
    "adminFirstName" text,
    "adminLastName" text,
    "companyGstNo" text,
    "companySize" text,
    "contactPersonEmail" text,
    "contactPersonFirstName" text,
    "contactPersonLastName" text,
    notes text,
    "registrationFile" text,
    "websiteUrl" text,
    "divisionId" text,
    "positionId" text,
    "zohoCustomerId" text,
    "isOnboarded" boolean DEFAULT false NOT NULL,
    "onBoardDate" timestamp(3),
    "autoCollect" boolean DEFAULT true NOT NULL,
    "isCp2" boolean DEFAULT false NOT NULL,
    "isCreditShow" boolean DEFAULT true NOT NULL,
    city text,
    country text,
    gst_treatment text,
    place_of_contact text,
    state text,
    street text,
    zip text,
    pan_no text,
    "paymentBy" text,
    "phoneCode" text
);

CREATE TABLE "User" (
    id text NOT NULL,
    username text,
    password text NOT NULL,
    "firstName" text NOT NULL,
    "lastName" text,
    email text,
    "emailVerifiedAt" timestamp(3),
    "phoneNumber" text,
    "phoneNumberVerifiedAt" timestamp(3),
    "socialLogin" "SocialLogin",
    remark text,
    "preferredLanguageId" text NOT NULL,
    "userInfo" text,
    "responseStyle" text,
    location text,
    "resetPasswordToken" text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdBy" text,
    status "UserStatus" NOT NULL,
    "profilePicture" text,
    "folderId" text,
    "isTourDone" boolean DEFAULT false NOT NULL,
    "isFirstLogin" boolean DEFAULT false NOT NULL,
    "isNoteBookDone" boolean DEFAULT false NOT NULL,
    "customPrompt" text,
    "isCustomPrompt" boolean DEFAULT false NOT NULL,
    "homeTourDone" boolean DEFAULT false NOT NULL,
    "isUnsubscribe" boolean DEFAULT false NOT NULL,
    "resetPasswordExpiresAt" timestamp(3),
    "sessionVersion" integer DEFAULT 0 NOT NULL,
    "researchAreas" text,
    "prefResponseStyle" text,
    "isOnboarded" boolean DEFAULT false NOT NULL,
    "mcpUrl" text,
    "maxCreditUsage" numeric(18,6) DEFAULT 0 NOT NULL,
    "fpAttempts" integer DEFAULT 0 NOT NULL,
    "fpLastAt" timestamp(3),
    "keycloakId" text,
    "studioPlatformSetting" boolean DEFAULT false NOT NULL
);

CREATE TABLE "OrganizationUser" (
    id text NOT NULL,
    "userId" text NOT NULL,
    status "Status" NOT NULL,
    remark text,
    "organizationId" text
);

CREATE TABLE "Package" (
    id text NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    status "Status" NOT NULL,
    remark text,
    "chatCount" integer,
    "messageCount" integer,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdBy" text,
    "tokenCount" integer,
    "documentSize" integer,
    "order" text,
    price numeric(10,2),
    "agentCount" integer,
    "proSearchCount" integer,
    "deepResearchCount" integer,
    credit integer,
    features jsonb,
    "zohoPlanCode" text,
    "yearlyPrice" numeric(10,2),
    "suitableFor" text,
    "useCases" text,
    "isCustomPrice" boolean DEFAULT false NOT NULL,
    "accentColor" text,
    "backgroundColor" text,
    "isWeekly" boolean DEFAULT false NOT NULL,
    "isWorkflowAgent" boolean DEFAULT true NOT NULL,
    "appLimit" integer,
    "appStorageLimit" integer,
    "zipSizeLimit" integer,
    "dbCount" integer,
    "dbSize" integer
);

CREATE TABLE "OrganizationPackage" (
    id text NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    "numberOfUser" integer NOT NULL,
    status "Status" NOT NULL,
    remark text,
    "organizationId" text NOT NULL,
    "packageId" text NOT NULL,
    "PayFrequency" "PayFrequency",
    "endDate" timestamp(3),
    "paymentStatus" "PaymentStatus",
    "startDate" timestamp(3),
    "isZohoSubCreated" boolean DEFAULT false NOT NULL,
    "zohoPlanCode" text,
    "zohoSubId" text,
    "cancelledAt" timestamp(3),
    "lastAllocatedAt" timestamp(3),
    "nextAllocationAt" timestamp(3),
    "packageIdForNextTerm" text,
    "isZohoRenew" boolean DEFAULT false NOT NULL,
    "cancelAt" timestamp(3),
    "zohoSubActivatedAt" timestamp(3),
    "zohoSubStatus" text,
    "zohoSubno" text
);

CREATE TABLE "Payment" (
    id text NOT NULL,
    amount numeric(18,6) NOT NULL,
    "transactionId" text,
    "paymentMethod" "PaymentMethod" NOT NULL,
    "paymentStatus" "PaymentStatus" NOT NULL,
    "paymentDetails" jsonb,
    "paymentDate" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp(3) NOT NULL,
    remark text,
    "packageId" text,
    "organizationId" text NOT NULL,
    "userId" text NOT NULL
);

CREATE TABLE "CreditWallets" (
    id text NOT NULL,
    type "CreditType" NOT NULL,
    allocated numeric(18,6) DEFAULT 0 NOT NULL,
    used numeric(18,6) DEFAULT 0 NOT NULL,
    "allocationDate" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "expiryDate" timestamp(3),
    "isActive" boolean DEFAULT true NOT NULL,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp(3) NOT NULL,
    details jsonb,
    amount numeric(12,6) DEFAULT 0.00 NOT NULL,
    "channelPartnerId" text,
    "creditsPurchased" numeric(18,6) DEFAULT 0 NOT NULL,
    "licenseId" text,
    "onboardingCharges" numeric(12,6) DEFAULT 0.00 NOT NULL,
    "organizationId" text,
    "paymentDetails" jsonb,
    "paymentMethod" "PaymentMethod",
    "paymentStatus" "PaymentStatus",
    "purchasedBy" text,
    "userId" text,
    "entityType" "EntityType" NOT NULL,
    "createdBy" text,
    "zohoHostedPageId" text,
    "zohoSubId" text,
    "addonId" text,
    "isAddon" boolean DEFAULT false NOT NULL,
    "cancelledAt" timestamp(3),
    "isManualCredit" boolean DEFAULT false NOT NULL,
    "rolledBack" numeric(18,6) DEFAULT 0 NOT NULL
);

CREATE TABLE "CreditTransaction" (
    id text NOT NULL,
    "entityType" "EntityType" NOT NULL,
    "transactionType" "TransactionType",
    "creditWalletId" text NOT NULL,
    "balanceBefore" numeric(18,6) NOT NULL,
    "balanceAfter" numeric(18,6) NOT NULL,
    "referenceId" text,
    description text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "channelPartnerId" text,
    "licenseId" text,
    "organizationId" text,
    "userId" text,
    amount numeric(12,6),
    "createdBy" text,
    credits numeric(18,6) NOT NULL,
    "rateCredit" numeric(18,6),
    "chatQueId" text,
    "flowId" text,
    "flowName" text,
    "flowVersionId" text,
    "pieceId" text,
    type text,
    context jsonb,
    "runId" text,
    steps jsonb,
    "taskCount" text,
    "agentName" text,
    "jobId" text
);

CREATE TABLE "FreeCreditUsage" (
    id text NOT NULL,
    "channelPartnerId" text,
    "organizationId" text,
    "userId" text,
    credits numeric(18,6) NOT NULL,
    "referenceId" text,
    description text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "flowId" text,
    "flowName" text,
    type text,
    "flowVersionId" text,
    "pieceId" text,
    "runId" text,
    context jsonb,
    steps jsonb,
    "taskCount" text,
    "createdBy" text
);

CREATE TABLE "ChatHistory" (
    id text NOT NULL,
    title text NOT NULL,
    "organizationUserId" text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdBy" text NOT NULL,
    "isDeleted" boolean DEFAULT false NOT NULL,
    "embeddingToken" integer,
    "chatType" "chatType" DEFAULT 'CHAT'::"chatType" NOT NULL,
    "isIncognito" boolean DEFAULT false NOT NULL,
    "docSize" integer,
    "inputToken" integer,
    "outputToken" integer,
    "notebookFolderId" text,
    "isNoState" boolean DEFAULT false NOT NULL,
    "focusId" text,
    "folderId" text,
    summary text,
    "convRefId" text,
    "modelName" text,
    "phoneNumber" text
);

CREATE TABLE "ChatQuestion" (
    id text NOT NULL,
    question text NOT NULL,
    "chatHistoryId" text NOT NULL,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdBy" text NOT NULL,
    "isProSearch" boolean DEFAULT false NOT NULL,
    "isFile" boolean DEFAULT false NOT NULL,
    "parentId" text,
    "docSize" integer,
    "embeddingToken" integer,
    "summInputToken" integer,
    "summOutputToken" integer,
    "hideFile" boolean DEFAULT false NOT NULL,
    summary text,
    "jobId" text,
    "fileStatus" text,
    "fileNameS3" text,
    "isDeepResearch" boolean DEFAULT false NOT NULL,
    "researchStep" integer DEFAULT 0 NOT NULL,
    "isMobile" boolean DEFAULT false NOT NULL
);

CREATE TABLE "LoginHistory" (
    id text NOT NULL,
    "userId" text NOT NULL,
    ip text,
    browser text,
    "browserVersion" text,
    os text,
    "osVersion" text,
    device text,
    "loginProvider" text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "orgId" text NOT NULL
);

CREATE TABLE "UsageTracking" (
    id text NOT NULL,
    "chatType" text,
    type text,
    model text,
    provider text,
    "promptTokens" integer DEFAULT 0,
    "completionTokens" integer DEFAULT 0,
    "embeddingToken" integer DEFAULT 0,
    "searchCount" integer DEFAULT 0,
    "userId" text,
    "orgId" text,
    "chatHistoryId" text,
    "folderId" text,
    "questionId" text,
    "summInputToken" integer DEFAULT 0,
    "summOutputToken" integer DEFAULT 0,
    "answerId" text,
    "docId" text,
    "notebookFolderId" text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "docSize" integer DEFAULT 0,
    "notebookDocId" text,
    "totalPrice" numeric(10,2),
    "mapCount" integer DEFAULT 0,
    "durationSec" text,
    "refId" text,
    "refDetail" text,
    "cachedTokens" integer DEFAULT 0,
    "storageTokens" integer DEFAULT 0
);

CREATE TABLE "Calls" (
    id text NOT NULL,
    "callRequestId" text,
    "callSid" text,
    "callStatus" text,
    "callDuration" text,
    "callDate" text,
    "fromNumber" text,
    "toNumber" text,
    "callDirection" text,
    "botId" text,
    "puchoAgentId" text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "orgId" text NOT NULL,
    "userId" text NOT NULL,
    "vendorId" text,
    "contextDetails" jsonb,
    "puchoAgentName" text,
    "endTime" timestamp(3),
    "startTime" timestamp(3),
    "durationSec" integer DEFAULT 0
);

CREATE TABLE "WaitlistUser" (
    id text NOT NULL,
    email text NOT NULL,
    name text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "ContactSales" (
    id text NOT NULL,
    "companySize" text NOT NULL,
    "companyName" text NOT NULL,
    "firstName" text NOT NULL,
    "lastName" text NOT NULL,
    email text NOT NULL,
    "phoneNumber" text,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "organizationId" text,
    "channelPartnerId" text,
    "businessNeeds" text
);

CREATE TABLE "CampaignLead" (
    id text NOT NULL,
    "campaignId" text NOT NULL,
    "firstName" text NOT NULL,
    "lastName" text NOT NULL,
    mobile text NOT NULL,
    "companyName" text,
    "emailId" text NOT NULL,
    remark text,
    status "SDRStatus" NOT NULL,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdBy" text,
    "jobId" text,
    "lastContactDate" timestamp(3),
    "lastResearchDate" timestamp(3),
    "leadScore" double precision,
    "researchData" jsonb,
    "emailSeqGenerated" boolean DEFAULT false NOT NULL,
    "needHuman" boolean DEFAULT false NOT NULL
);

CREATE TABLE "CreditUsageError" (
    id text NOT NULL,
    "organizationId" text,
    "userId" text,
    "referenceId" text,
    "chatQueId" text,
    errors jsonb,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE "SubscriptionUpgrade" (
    id text NOT NULL,
    "orgId" text NOT NULL,
    "zohoSubscriptionId" text,
    "oldPlanId" text NOT NULL,
    "newPlanId" text NOT NULL,
    "creditNoteId" text,
    "creditAmount" numeric(10,2),
    "upgradeStatus" "PaymentStatus" DEFAULT 'PENDING'::"PaymentStatus" NOT NULL,
    "creditNoteStatus" "CreditNoteStatus" DEFAULT 'open'::"CreditNoteStatus" NOT NULL,
    "zohoHostedPageId" text,
    details jsonb,
    "createdAt" timestamp(3) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "expiresAt" timestamp(3),
    remark text,
    "retryCount" integer DEFAULT 0 NOT NULL
);

ALTER TABLE "Language" ADD PRIMARY KEY (id);
ALTER TABLE "ChannelPartner" ADD PRIMARY KEY (id);
ALTER TABLE "Organization" ADD PRIMARY KEY (id);
ALTER TABLE "User" ADD PRIMARY KEY (id);
ALTER TABLE "OrganizationUser" ADD PRIMARY KEY (id);
ALTER TABLE "Package" ADD PRIMARY KEY (id);
ALTER TABLE "OrganizationPackage" ADD PRIMARY KEY (id);
ALTER TABLE "Payment" ADD PRIMARY KEY (id);
ALTER TABLE "CreditWallets" ADD PRIMARY KEY (id);
ALTER TABLE "CreditTransaction" ADD PRIMARY KEY (id);
ALTER TABLE "FreeCreditUsage" ADD PRIMARY KEY (id);
ALTER TABLE "ChatHistory" ADD PRIMARY KEY (id);
ALTER TABLE "ChatQuestion" ADD PRIMARY KEY (id);
ALTER TABLE "LoginHistory" ADD PRIMARY KEY (id);
ALTER TABLE "UsageTracking" ADD PRIMARY KEY (id);
ALTER TABLE "Calls" ADD PRIMARY KEY (id);
ALTER TABLE "WaitlistUser" ADD PRIMARY KEY (id);
ALTER TABLE "ContactSales" ADD PRIMARY KEY (id);
ALTER TABLE "CampaignLead" ADD PRIMARY KEY (id);
ALTER TABLE "CreditUsageError" ADD PRIMARY KEY (id);
ALTER TABLE "SubscriptionUpgrade" ADD PRIMARY KEY (id);
